const Advance_state = {
    docid: "",
    docdate: "",
    idcard: "",
    fromDate: "",
    toDate: "",
    empname:"",
    category:"",
    finyear:"",
    advtype:"",
    total:'0',
    preloan:'0',
    totalloan:'0',
    predue:'0',
    ins:'0',
    remark:"",
    paycode:"",
    fincode:"",
    leaveType_options: [],
    category_options:[],
    tltype_options:[],
    fltype_options:[],
    ltype_options:[],
    fin_options:[],
    adv_options:[],
    pay_options:[]
  };
  
  const advance_Meta = [
    { state: "category", id: "Advance_state", label: "Category Type", style: { full: true }, type: "select", option_data: "category_options" },
    { state: "docid", id: "Advance_state", label: "DocId", style: { full: true } , props: { editable: false }},
    { state: "finyear", id: "Advance_state", label: "Fin Year", style: { full: false }, type: "select", option_data: "fin_options",addOnVal_State:"fincode",addOnVal_Key:"finId"},
    { state: "advtype", id: "Advance_state", label: "ADV Type", style: { full: false }, type: "select", option_data: "adv_options" },
    { state: "paytype", id: "Advance_state", label: "Pay Type", style: { full: false }, type: "select", option_data: "pay_options" },
    { state: "docdate", id: "Advance_state", label: "Document Date", style: { full: false}, type: "date" ,props:{editable: false }},
    { state: "idcard", id: "Advance_state", label: "ID Card", style: { full: false }, props: { editable: false } },
    { state: "empname", id: "Advance_state", label: "Employee Name", style: { full: false }, props: { editable: false } },
    { state: "fromDate", id: "Advance_state", label: "From Date", style: { full: false}, type: "date" },
    { state: "total", id: "Advance_state", label: "Loan Requirement", style: { full: false }},
    { state: "preloan", id: "Advance_state", label: "Previous Loan Amt", style: { full: false },props: { keyboardType:"numeric" ,editable:false}},
    { state: "totalloan", id: "Advance_state", label: "Total Loan Amt", style: { full: false },props: { keyboardType:"numeric" ,editable: false }},
    { state: "predue", id: "Advance_state", label: "Previous Due Amt", style: { full: false },props: { keyboardType:"numeric" , editable: false}},
    { state: "due", id: "Advance_state", label: "Due Amt", style: { full: false },props: { keyboardType:"numeric" }},
    { state: "ins", id: "Advance_state", label: "No.Of Instalment", style: { full: false },props: { keyboardType:"numeric",editable: false }},
    { state: "toDate", id: "Advance_state", label: "To Date", style: { full: false}, type: "date" ,props: { editable: false }},
    { state: "remark", id: "Advance_state", label: "Remark", style: { full: true,height:130 } },
  ];
  export {Advance_state,advance_Meta}